Added Timm packages

diff --git a/nvidia-driver b/nvidia-driver
--- a/nvidia-driver
+++ b/nvidia-driver
@@ -1,4 +1,4 @@
-#! /bin/bash
+#! /bin/bash -x
 # Copyright (c) 2018, NVIDIA CORPORATION. All rights reserved.
 
 set -eu
@@ -278,16 +278,16 @@ init() {
     _unload_driver || exit 1
     _unmount_rootfs
 
-    if _kernel_requires_package; then
-        _update_package_cache
-        _resolve_kernel_version || exit 1
-        _install_prerequisites
-        _create_driver_package
-        _remove_prerequisites
-        _cleanup_package_cache
-    fi
+#    if _kernel_requires_package; then
+#        _update_package_cache
+#        _resolve_kernel_version || exit 1
+#        _install_prerequisites
+#        _create_driver_package
+#        _remove_prerequisites
+#        _cleanup_package_cache
+#    fi
 
-    _install_driver
+#    _install_driver
     _load_driver
     _mount_rootfs
     _write_kernel_update_hook
